# PostgreSQL Client Authentication Configuration File
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Локальное подключение для postgres (для инициализации)
local   all             postgres                                trust

# mTLS аутентификация для пользователей с их базами данных
hostssl apidoc          apidoc          0.0.0.0/0               cert clientcert=verify-full
hostssl apiman          apiman          0.0.0.0/0               cert clientcert=verify-full
hostssl kpi             kpi             0.0.0.0/0               cert clientcert=verify-full

# Запрет всех остальных подключений
hostssl all             all             0.0.0.0/0               reject
host    all             all             0.0.0.0/0               reject
