---
# Secret с сертификатами для пользователя apidoc
apiVersion: v1
kind: Secret
metadata:
  name: postgres-apidoc-certs
  namespace: postgres-client
type: Opaque
data:
  ca.crt: PLACEHOLDER_CA_CRT
  tls.crt: PLACEHOLDER_TLS_CRT
  tls.key: PLACEHOLDER_TLS_KEY

---
# Secret с сертификатами для пользователя apiman
apiVersion: v1
kind: Secret
metadata:
  name: postgres-apiman-certs
  namespace: postgres-client
type: Opaque
data:
  ca.crt: PLACEHOLDER_CA_CRT
  tls.crt: PLACEHOLDER_TLS_CRT
  tls.key: PLACEHOLDER_TLS_KEY

---
# Secret с сертификатами для пользователя kpi
apiVersion: v1
kind: Secret
metadata:
  name: postgres-kpi-certs
  namespace: postgres-client
type: Opaque
data:
  ca.crt: PLACEHOLDER_CA_CRT
  tls.crt: PLACEHOLDER_TLS_CRT
  tls.key: PLACEHOLDER_TLS_KEY
