---
# DestinationRule для apidoc с mTLS
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-apidoc-mtls
  namespace: postgres-client
spec:
  host: srv8-objkrugess.mfactory.nxcloud.nexign.com
  exportTo:
    - "."
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/apidoc/tls.crt
      privateKey: /etc/certs/apidoc/tls.key
      caCertificates: /etc/certs/apidoc/ca.crt
      sni: srv8-objkrugess.mfactory.nxcloud.nexign.com
